### ISSUE TITLE
Click comes out long press

### ISSUE THREAD

**Issue by maticrivo** [EverythingMe/magneto#5]
In multiple incidences, we've noticed that a simple el.click() results in long press, messing up tests. Witnessed on Nexus 4 and Nexus 7.
The cause isn't clear.

**Comment by ranbena** [comment]
Closing this for the following reasons:
1. Upgraded OS to Lollipop and doesn't happen anymore.
2. Did not get this complaint from others at all.

Plz reopen if this reoccurs.
